/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.demo;

import java.sql.*;

public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        /*
        String URL = "jdbc:mysql://localhost:3306/laravel";
        String USERNAME = "root";
        String PASSWORD = "";
        try {
            Connection connection = DriverManager.getConnection(URL, USERNAME, PASSWORD);

            String query = "SELECT name FROM users LIMIT 1";
            PreparedStatement test = connection.prepareStatement(query);
            ResultSet results = test.executeQuery();

            if (results.next()) {
                System.out.println(results.getString("name"));
            }


        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }
        */
    }
}
